name: filamentgestion
description: "Projet flutter du site filamentgestion.fr"
publish_to: 'none'
version: 0.0.1-dev

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  package_info: ^2.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
